### ISSUE TITLE
where is the code

### ISSUE THREAD

**Issue by pyqpinbo** [paidamoyo/survival_cluster_analysis#1]
I just read your paper: survival cluster analysis, but I cannot find the code and data. Could you please update them? Many thanks!

**Comment by paidamoyo** [comment]
Hi @pyqpinbo, thanks for your interest in our work! We are currently cleaning up all the code and should have it uploaded by the end of next week.

**Comment by paidamoyo** [comment]
Hi @pyqpinbo, the code has been added. Closing this issue.

**Comment by pyqpinbo** [comment]
Thanks a lot!

Paidamoyo Chapfuwa <notifications@github.com> 于2020年3月17日周二 上午10:23写道：
