### ISSUE TITLE
Unable to locate dataset in the example notebooks

### ISSUE THREAD

**Issue by JoJoDeee** [paidamoyo/survival_cluster_analysis#5]
Hi Dr. Chapfuwa,

I'm very interested in your method and want to compare the performance with the cluster method that we are working on. I was trying to run the clustering notebook but it seems the data directory is missing quite a lot files. For example in the sleep data, I was unable to find the numpy file of "Test_empirical_t.npy", "Test_empirical_e.npy" and in the sleep.py file, the csv file "final_sleep_data.csv", "final_status_cvd.csv" and "final_any_cvd" are missing. Can you update the directory? 

Thank you! 
Hao

**Comment by paidamoyo** [comment]
Hi Hao. Thanks for your interest. 

 The  `Clustering.ipynb` evaluation notebook uses the [SLEEP](https://sleepdata.org/datasets/shhs) dataset, which is available upon request. Once you have access to the **SLEEP** dataset, you could use the `sleep_data.py`  preprocessing script to generate these files. 

Note that the **FLCHAIN** and  **SUPPORT** datasets are publicly available and could be used to test the framework end-to-end. See **README**  under *DATA* section for more details.

Best,
Ash
